name: Generate and upload ical to Gist

on: 
  workflow_dispatch: # manually run 
  schedule:
    - cron:  '0 0 * * *' # daily at midnight https://cron.help/#0_0_*_*_*

jobs:
  generate-then-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write # be able to upload Gist
    steps: 
    - uses: actions/checkout@v3
    
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - run: deno run --allow-write=./ynab_scheduled.ics --allow-net=api.ynab.com --allow-env="YNAB_PERSONAL_ACCESS_TOKEN,YNAB_BUDGET_ID" generate-ical.ts  
      env: 
        YNAB_PERSONAL_ACCESS_TOKEN: ${{ secrets.YNAB_PERSONAL_ACCESS_TOKEN }}
        YNAB_BUDGET_ID: ${{ secrets.YNAB_BUDGET_ID }}

    - name: Read ical file
      id: ical
      uses: juliangruber/read-file-action@v1
      with:
        path: ./example.ics
    
    - name: Upload ical to Gist
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.gists.update({
            gist_id: "${{ secrets.GIST_ID }}",
            description: `YNAB scheduled transactions calendar. Generated by github.com/levibostian/ynab-scheduled-ical. Last updated: ${new Date().toString()}`,
            files: {
              "events.ical": {
                "content": "${{ steps.ical.outputs.content }}"
              }
            }
          });