name: Generate and upload ical to Gist

on: 
  workflow_dispatch: # manually run 
  schedule:
    - cron:  '0 0 * * *' # daily at midnight https://cron.help/#0_0_*_*_*

jobs:
  generate-then-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write # be able to upload Gist
    steps: 
    - uses: actions/checkout@v3
    
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - run: deno run --allow-write=./ynab_scheduled.ics --allow-read=./ --allow-net=api.ynab.com,api.github.com --allow-env="YNAB_PERSONAL_ACCESS_TOKEN,YNAB_BUDGET_NAME,GIST_PERSONAL_ACCESS_TOKEN" generate-ical.ts
      env: 
        YNAB_PERSONAL_ACCESS_TOKEN: ${{ secrets.YNAB_PERSONAL_ACCESS_TOKEN }}
        YNAB_BUDGET_NAME: ${{ secrets.YNAB_BUDGET_NAME }}
        GIST_PERSONAL_ACCESS_TOKEN: ${{ secrets.GIST_PERSONAL_ACCESS_TOKEN }}
    
    