name: Generate and upload ical to Gist

on: 
  workflow_dispatch: # manually run 
  pull_request: # to be able to test that it works
  schedule:
    - cron:  '0 0 * * *' # daily at midnight https://cron.help/#0_0_*_*_*

jobs:
  generate-then-upload:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - name: Run script 
      env: 
        YNAB_PERSONAL_ACCESS_TOKEN: ${{ secrets.YNAB_PERSONAL_ACCESS_TOKEN }}
        YNAB_BUDGET_NAME: ${{ secrets.YNAB_BUDGET_NAME }}
        GIST_PERSONAL_ACCESS_TOKEN: ${{ secrets.GIST_PERSONAL_ACCESS_TOKEN }}
      run: |
        deno cache --reload --lock=deno.lock deps.ts
        deno run --lock --cached-only --allow-write=./ynab_scheduled.ics --allow-read=./ --allow-net=api.ynab.com,api.github.com --allow-env="YNAB_PERSONAL_ACCESS_TOKEN,YNAB_BUDGET_NAME,GIST_PERSONAL_ACCESS_TOKEN" generate-ical.ts
      
